apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: shorturl
    env: base
  name: shorturl
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shorturl-frontend
    env: base
  name: shorturl-frontend
  namespace: shorturl
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: shorturl-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shorturl-frontend
    env: base
  name: shorturl-frontend
  namespace: shorturl
spec:
  selector:
    matchLabels:
      app: shorturl-frontend
  template:
    metadata:
      labels:
        app: shorturl-frontend
        env: base
    spec:
      containers:
      - image: shorturl-frontend:v0.0.1
        name: shorturl-frontend
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: shorturl-frontend
    env: base
  name: shorturl-frontend
  namespace: shorturl
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shorturl-frontend
  targetCPUUtilizationPercentage: 70
